package selenium.ide;

// Generated by Selenium IDE

import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.*;
import org.openqa.selenium.edge.EdgeDriver;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;

/*
    Alessandro MADDALENA 0294043
*/

/*
   This test retrieves a random date from randomlists.com and verifies that it is in the future.
*/

public class TestRandomNextDate {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.edge.driver", "src/test/java/selenium/Driver/msedgedriver.exe");
        driver = new EdgeDriver();
        js = (JavascriptExecutor) driver;
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testRandomNextDate() {

        //Setup
        driver.get("https://www.randomlists.com/random-date");
        driver.manage().window().setSize(new Dimension(1010, 662));

        // Get a random date from randomlists.com
        driver.findElement(By.cssSelector(".fc-cta-consent > .fc-button-label")).click();
        js.executeScript("window.scrollTo(0,264)");
        driver.findElement(By.id("rand_options_qty")).click();
        driver.findElement(By.id("rand_options_qty")).sendKeys(Keys.BACK_SPACE);
        driver.findElement(By.id("rand_options_qty")).sendKeys("1");
        driver.findElement(By.id("rand_options_dup")).click();
        driver.findElement(By.cssSelector("p > .button")).click();
        WebElement dateElement = driver.findElement(By.xpath("//span[@class='rand_large']"));

        // Convert the date to a LocalDate
        String dateString = dateElement.getText();
        LocalDate date = LocalDate.parse(dateString, DateTimeFormatter.ofPattern("MMM. d, yyyy", Locale.ENGLISH));

        // Get today's date
        LocalDate today = LocalDate.now();

        // Assert that the date from the website is after today
        Assert.assertTrue(date.isAfter(today));
    }
}
